(() => {
  'use strict';
  const W=360,H=640, HUD=88, PLAYER_Y=548, ASSET='./assets/';
  const canvas=document.querySelector('#game'), ctx=canvas.getContext('2d'), bgm=document.querySelector('#bgm'); ctx.imageSmoothingEnabled=true;
  const ui={start:document.querySelector('#start-screen'),result:document.querySelector('#result-screen'),startBtn:document.querySelector('#start-button'),restart:document.querySelector('#restart-button'),challenge:document.querySelector('#challenge-button'),share:document.querySelector('#share-button'),cardPanel:document.querySelector('#share-card-panel'),cardCanvas:document.querySelector('#share-card-canvas'),saveCard:document.querySelector('#save-card-button'),closeCard:document.querySelector('#close-card-button'),mute:document.querySelector('#mute-button'),title:document.querySelector('#result-title'),copy:document.querySelector('#result-copy'),score:document.querySelector('#result-score'),combo:document.querySelector('#result-combo'),bull:document.querySelector('#result-bull'),high:document.querySelector('#result-high')};
  const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
  const names=['牛来股份','牛市科技','回本股份','解套集团','满仓科技','东方牛来','牛来重工','梭哈科技'];
  const cheers=['牛来了！','牛真的来了！','这次不一样！','突破！','龙一！','全体起立！'];
  const specs={
    up:{image:'stock-up',score:100,bull:10,index:5,weight:35,label:'+3.21%',kind:'up'}, strongUp:{image:'stock-up',score:200,bull:12,index:10,weight:15,label:'+5.88%',kind:'up'}, nearLimit:{image:'stock-up',score:500,bull:18,index:25,weight:8,label:'+9.99%',kind:'up'}, limitUp:{image:'limit-up',score:1000,bull:25,index:50,weight:4,label:'涨停！',kind:'up'},
    down:{image:'stock-down',damage:1,index:-15,weight:20,label:'-3.21%',kind:'down'}, strongDown:{image:'stock-down',damage:2,index:-35,weight:7,label:'-5.88%',kind:'down'}, limitDown:{image:'limit-down',damage:1,index:-50,weight:3,label:'跌停',kind:'down',reset:true}, rocket:{image:'rocket',effect:'rocket',weight:3,label:'火箭',kind:'special'}, liquor:{image:'liquor',effect:'heal',weight:2,label:'白酒',kind:'special'}, news:{image:'good-news',effect:'news',weight:2,label:'利好',kind:'special'}, bear:{image:'bear',effect:'bear',weight:1,label:'熊出没',kind:'down'}
  };
  const images={}; const load=(key,path)=>new Promise(resolve=>{const i=new Image();i.onload=()=>resolve(images[key]=i);i.onerror=()=>resolve();i.src=path;});
  const shareImages={},loadShare=(key,path)=>new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(shareImages[key]=image);image.onerror=()=>reject(new Error(`无法加载分享卡素材：${path}`));image.src=path;});
  let shareAssetsReady=null,shareCardBlob=null,shareHero=null;
  const assets=[['normal','backgrounds/normal-market.png'],['bull','backgrounds/bull-market.png'],['idle','character/processed/idle.png'],['run-left','character/processed/run-left.png'],['run-right','character/processed/run-right.png'],['catch-up','character/processed/catch-up.png'],['hurt-down','character/processed/hurt-down.png'],['bull-run','character/processed/bull-run.png'],...['stock-up','limit-up','stock-down','limit-down','rocket','liquor','good-news','bear'].map(n=>[n,`items/processed/${n}.png`])];
  const shareAssetList=[['background','share-card/share-card-background.png'],['effects','share-card/share-card-effects.png'],['hero','share-card/niulai-hero.png'],['ui','share-card/share-card-ui-sheet.png']];
  let state='START', last=0, raf=0, keys=new Set(), pointer=null, muted=localStorage.getItem('niulai-muted')==='1', audio=null;
  const BGM_LOOP_AT=15;
  let g={};
  function fitCanvas(){const rect=canvas.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1),width=Math.round(rect.width*dpr),height=Math.round(rect.height*dpr);if(canvas.width!==width||canvas.height!==height){canvas.width=width;canvas.height=height;ctx.setTransform(width/W,0,0,height/H,0,0);ctx.imageSmoothingEnabled=true;}}
  function reset(){g={time:60,score:0,lives:3,combo:0,maxCombo:0,bull:0,index:3248,bullMode:0,bullCount:0,spawn:0.55,items:[],floaters:[],particles:[],playerX:W/2,facing:0,invincible:0,catching:0,hurt:0,rocket:0,news:0,bear:0,flash:0,shake:0,announced:new Set(),nextId:0};}
  function rand(a,b){return a+Math.random()*(b-a)} function pick(a){return a[Math.floor(Math.random()*a.length)]} function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
  function start(){reset(); state='PLAYING'; ui.start.hidden=true;ui.result.hidden=true;last=performance.now(); cancelAnimationFrame(raf);raf=requestAnimationFrame(loop);playBgm();beep(500,.07);}
  function selectType(){const allowed=g.bullMode||g.news>0?['up','strongUp','nearLimit','limitUp']:Object.keys(specs);let bag=[];allowed.forEach(k=>{let weight=specs[k].weight;if(g.bear>0&&specs[k].kind==='down')weight*=2; for(let i=0;i<weight;i++)bag.push(k)});return pick(bag)}
  function spawn(){if(g.items.length>=12)return; const type=selectType(),s=specs[type],elapsed=60-g.time,level=Math.floor(elapsed/15),r=type==='bear'?30:25; let x=rand(r,W-r); const danger=s.damage>1||type==='limitDown'; if(danger){const recent=g.items.filter(v=>v.y<150&&v.danger);if(recent.length>=2)x=rand(40,W-40)} g.items.push({id:g.nextId++,type,s,x,y:HUD-15,vy:rand(140,190)*(1+level*.1)*(g.bullMode?1.25:1),size:type==='bear'?47:39,angle:rand(-.1,.1),danger,name:s.kind==='up'||s.kind==='down'?pick(names):'',used:false});}
  function addFloat(text,x,y,color='#fff',size=16){g.floaters.push({text,x,y,color,size,life:1});}
  function event(text,color='#fff'){addFloat(text,W/2,150,color,22);g.flash=reduced?0:.25;}
  function milestone(){for(const [value,text] of [[4000,'突破！'],[5178,'熟悉的位置！'],[6124,'见证历史！'],[10000,'这次不一样！']])if(g.index>=value&&!g.announced.has(value)){g.announced.add(value);event(text,'#ffd660');}}
  function collect(item){if(item.used)return;item.used=true;const s=item.s;g.catching=.23;
    if(s.kind==='up'){g.combo++;g.maxCombo=Math.max(g.maxCombo,g.combo);const multiplier=(g.bullMode?3:1)*(g.rocket>0?2:1),gain=s.score*multiplier+Math.min(g.combo,20)*5;g.score+=gain;g.bull=clamp(g.bull+s.bull+(g.combo%5===0?5:0),0,100);g.index+=Math.ceil(s.score/20)*(g.bullMode?3:1);addFloat(`+${gain}`,item.x,item.y,'#ff645b',s.score>=1000?24:17);beep(s.score>=1000?880:650,.07);if(s.score>=1000){event('涨停！','#ffd15c');burst(item.x,item.y,'#ffbe4c',18)}if(g.bull>=100&&!g.bullMode)bullMode();}
    else if(s.effect==='rocket'){g.rocket=5;addFloat('火箭加速！',item.x,item.y,'#ffc45a',18);event('红股价值 ×2','#ffc45a');beep(930,.1)}
    else if(s.effect==='heal'){g.lives=Math.min(3,g.lives+1);addFloat('+1 牛命',item.x,item.y,'#fff0ca',18);beep(750,.08)}
    else if(s.effect==='news'){g.news=5;addFloat('只涨不跌！',item.x,item.y,'#ffd65e',18);event('利好来袭！','#ffd65e');}
    else if(s.effect==='bear'){g.combo=0;g.bear=3;addFloat('熊出没！',item.x,item.y,'#b58a6c',18);beep(150,.12)}
    else damage(item);
    milestone();burst(item.x,item.y,s.kind==='up'?'#ff5d54':'#78d86c',8);
  }
  function damage(item){if(g.invincible>0)return;const s=item.s;g.combo=0;if(s.reset)g.bull=0;g.lives-=s.damage||1;g.index=Math.max(2800,g.index+(s.index||-25));g.invincible=.7;g.hurt=.42;g.flash=reduced?0:.18;g.shake=reduced?0:.18;addFloat(s.reset?'牛气清零！':'绿跌伤牛！',item.x,item.y,'#74db76',18);beep(120,.15);if(g.lives<=0)gameOver();}
  function bullMode(){state='BULL_MODE';g.bullMode=8;g.bullCount++;g.bullCheer=pick(cheers);g.items=g.items.filter(i=>i.s.kind!=='down');g.shake=reduced?0:.35;g.flash=reduced?0:.35;event('牛市来了！','#fff2bd');beep(1100,.16);setTimeout(()=>beep(1450,.18),180)}
  function burst(x,y,color,n){for(let i=0;i<n;i++)g.particles.push({x,y,vx:rand(-70,70),vy:rand(-100,20),life:rand(.35,.7),color,size:rand(2,5)});}
  function update(dt){ if(state!=='PLAYING'&&state!=='BULL_MODE')return; g.time-=dt; if(g.time<=0){g.time=0;gameOver();return} const level=Math.floor((60-g.time)/15);g.spawn-=dt;if(g.spawn<=0){spawn();g.spawn=rand(.65,.85)*Math.pow(.92,level)*(g.bullMode?.75:1)}
    ['invincible','catching','hurt','rocket','news','bear','flash','shake'].forEach(k=>g[k]=Math.max(0,g[k]-dt));if(g.bullMode){g.bullMode=Math.max(0,g.bullMode-dt);if(!g.bullMode){state='PLAYING';g.bull=0;event('牛市收盘','#ffe6b1')}}
    const target=pointer==null?null:pointer;let dir=(keys.has('ArrowRight')||keys.has('d')?1:0)-(keys.has('ArrowLeft')||keys.has('a')?1:0);if(dir===0&&target!=null){const d=target-g.playerX;dir=Math.abs(d)<2?0:Math.sign(d)}g.playerX=clamp(g.playerX+dir*290*dt,42,W-42);g.facing=dir;
    for(const item of g.items){item.y+=item.vy*dt;item.angle+=dt*.7;if(!item.used&&g.invincible<=0&&Math.abs(item.x-g.playerX)<item.size*.62+28&&item.y+item.size*.48>PLAYER_Y&&item.y-item.size*.48<PLAYER_Y+65)collect(item)}g.items=g.items.filter(i=>!i.used&&i.y-i.size< H+24);
    for(const f of g.floaters){f.y-=34*dt;f.life-=dt}g.floaters=g.floaters.filter(f=>f.life>0);for(const p of g.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=150*dt;p.life-=dt}g.particles=g.particles.filter(p=>p.life>0);
  }
  function drawImage(img,x,y,w,h){if(img)ctx.drawImage(img,x-w/2,y-h/2,w,h);}
  function drawBackground(){const bg=images[g.bullMode?'bull':'normal'];if(bg)ctx.drawImage(bg,0,0,W,H);else {ctx.fillStyle=g.bullMode?'#6c1717':'#1b3147';ctx.fillRect(0,0,W,H)}ctx.fillStyle='rgba(5,13,24,.18)';ctx.fillRect(0,0,W,H);}
  function drawHud(){ctx.save();ctx.textAlign='left';ctx.fillStyle='rgba(8,13,24,.78)';ctx.fillRect(0,0,W,HUD);ctx.fillStyle='#fff';ctx.font='700 12px system-ui';ctx.fillText(`上证指数 ${g.index.toFixed(2)} ${g.index>=3248?'↑':'↓'}`,12,22);ctx.fillStyle='#ffdd6b';ctx.font='900 17px system-ui';ctx.fillText(`${Math.round(g.score)}`,12,47);ctx.fillStyle='#d7ddea';ctx.font='700 11px system-ui';ctx.fillText('当前分数',12,62);ctx.textAlign='right';ctx.fillStyle='#fff';ctx.font='900 18px system-ui';ctx.fillText(`${Math.ceil(g.time)}s`,W-12,25);ctx.font='700 12px system-ui';ctx.fillStyle='#f4d7a2';ctx.fillText(`连涨 x${g.combo}`,W-12,48);ctx.fillStyle='#fff';ctx.font='16px system-ui';ctx.fillText('🐂'.repeat(g.lives)+'○'.repeat(3-g.lives),W-12,70);ctx.textAlign='left';ctx.fillStyle='#2a3447';ctx.fillRect(12,72,170,8);ctx.fillStyle=g.bullMode?'#ffbe4c':'#ff5b51';ctx.fillRect(12,72,170*(g.bull/100),8);ctx.strokeStyle='#fff7';ctx.strokeRect(12,72,170,8);ctx.fillStyle='#fff';ctx.font='700 10px system-ui';ctx.fillText(g.bullMode?`牛市 ${g.bullMode.toFixed(1)}s ×3`:`牛气 ${Math.round(g.bull)}%`,188,80);ctx.restore();}
  function draw(){fitCanvas();ctx.clearRect(0,0,W,H);ctx.save();if(g.shake>0){ctx.translate(rand(-3,3),rand(-3,3))}drawBackground();for(const item of g.items){ctx.save();ctx.translate(item.x,item.y);ctx.rotate(item.angle);drawImage(images[item.s.image],0,0,item.size,item.size);ctx.restore();if(item.s.kind==='up'||item.s.kind==='down'){ctx.textAlign='center';ctx.font='900 9px system-ui';ctx.fillStyle=item.s.kind==='up'?'#ff6a61':'#78db70';ctx.fillText(item.s.label,item.x,item.y+item.size*.68);ctx.fillStyle='#fff';ctx.font='700 7px system-ui';ctx.fillText(item.name,item.x,item.y-item.size*.62)}}
    for(const p of g.particles){ctx.globalAlpha=p.life*1.5;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;
    const action=g.hurt>0?'hurt-down':g.bullMode?'bull-run':g.catching>0?'catch-up':g.facing<0?'run-left':g.facing>0?'run-right':'idle';if(g.invincible>0&&Math.floor(g.invincible*18)%2===0)ctx.globalAlpha=.45;drawImage(images[action],g.playerX,PLAYER_Y+35,g.bullMode?112:96,g.bullMode?112:96);ctx.globalAlpha=1;
    for(const f of g.floaters){ctx.globalAlpha=Math.min(1,f.life*2);ctx.textAlign='center';ctx.font=`900 ${f.size}px system-ui`;ctx.strokeStyle='#111a';ctx.lineWidth=3;ctx.strokeText(f.text,f.x,f.y);ctx.fillStyle=f.color;ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1;drawHud();if(g.flash>0){ctx.fillStyle=g.bullMode?'rgba(255,95,60,.24)':'rgba(255,255,255,.18)';ctx.fillRect(0,0,W,H)}if(g.bullMode){ctx.textAlign='center';ctx.fillStyle='#fff5c8';ctx.font='900 23px system-ui';ctx.fillText('牛市来了！',W/2,116);ctx.font='700 12px system-ui';ctx.fillStyle='#fff';ctx.fillText(g.bullCheer,W/2,136)}ctx.restore();}
  function loop(now){const dt=Math.min(.05,(now-last)/1000||0);last=now;update(dt);draw();if(state==='PLAYING'||state==='BULL_MODE')raf=requestAnimationFrame(loop)}
  function titleFor(score){return score<1000?'韭菜苗':score<3000?'老股民':score<6000?'抄底侠':score<10000?'私募大佬':score<20000?'牛市发动机':'牛来本人'}
  function gameOver(){if(state==='GAME_OVER')return;state='GAME_OVER';cancelAnimationFrame(raf);const high=Math.max(+localStorage.getItem('niulai-high')||0,Math.round(g.score));localStorage.setItem('niulai-high',high);const title=titleFor(g.score);ui.title.textContent=title;ui.copy.textContent=`你把大A接到了 ${g.index.toFixed(0)} 点，获得称号「${title}」。牛来，终将抵达。`;ui.score.textContent=Math.round(g.score);ui.combo.textContent=`x${g.maxCombo}`;ui.bull.textContent=`${g.bullCount} 次`;ui.high.textContent=high;ui.result.hidden=false;beep(250,.16)}
  function screenPoint(e){const r=canvas.getBoundingClientRect();return clamp((e.clientX-r.left)/r.width*W,35,W-35)}
  function initAudio(){if(!audio)audio=new (window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume();}
  function prepareShareHero(source){const buffer=document.createElement('canvas');buffer.width=source.naturalWidth;buffer.height=source.naturalHeight;const bctx=buffer.getContext('2d');bctx.drawImage(source,0,0);const data=bctx.getImageData(0,0,buffer.width,buffer.height);for(let i=0;i<data.data.length;i+=4){const r=data.data[i],gch=data.data[i+1],b=data.data[i+2];if(gch>115&&gch>r*1.35&&gch>b*1.35)data.data[i+3]=0}bctx.putImageData(data,0,0);return buffer;}
  function ensureShareAssets(){if(!shareAssetsReady)shareAssetsReady=Promise.all(shareAssetList.map(([key,path])=>loadShare(key,ASSET+path))).then(()=>{shareHero=prepareShareHero(shareImages.hero)});return shareAssetsReady;}
  function cardText(c,x,y,text,size,align='center',color='#ffe19a'){c.save();c.textAlign=align;c.textBaseline='middle';c.font=`900 ${size}px "Microsoft YaHei", sans-serif`;c.lineWidth=Math.max(2,size*.045);c.strokeStyle='#64150c';c.strokeText(text,x,y);c.fillStyle=color;c.fillText(text,x,y);c.restore();}
  function cardPanel(c,sx,sy,sw,sh,dx,dy,dw,dh){c.drawImage(shareImages.ui,sx,sy,sw,sh,dx,dy,dw,dh)}
  function drawQrPlaceholder(c){const x=814,y=1230,size=160;cardPanel(c,882,651,335,345,x-13,y-13,size+26,size+26);c.fillStyle='#fff8e7';c.fillRect(x,y,size,size);c.fillStyle='#2b1007';for(let row=0;row<13;row++)for(let col=0;col<13;col++){const finder=(row<4&&col<4)||(row<4&&col>8)||(row>8&&col<4);if(finder||((row*7+col*11+row*col)%5===0))c.fillRect(x+10+col*10,y+10+row*10,7,7)}c.fillStyle='rgba(255,248,231,.95)';c.fillRect(x+14,y+60,size-28,42);c.fillStyle='#7a1b0e';c.font='900 14px "Microsoft YaHei"';c.textAlign='center';c.fillText('二维码占位',x+size/2,y+80);c.font='700 10px "Microsoft YaHei"';c.fillText('上线后生成',x+size/2,y+98);}
  async function buildShareCard(){await ensureShareAssets();const c=ui.cardCanvas,card=c.getContext('2d'),w=c.width,h=c.height;card.clearRect(0,0,w,h);card.drawImage(shareImages.background,0,0,w,h);card.save();card.globalAlpha=.8;card.globalCompositeOperation='screen';card.drawImage(shareImages.effects,0,0,w,h);card.restore();cardPanel(card,272,44,704,136,266,24,548,106);cardText(card,w/2,77,'牛来：牛市接接乐',42);cardText(card,w/2,170,'我把大A接到了',66);cardText(card,w/2,330,`${Math.round(g.index)}`,205,'center','#ffe49a');cardText(card,875,364,'点',64,'left','#ffe49a');card.save();card.shadowColor='#ff351a';card.shadowBlur=28;card.drawImage(shareHero,145,376,790,1032);card.restore();cardPanel(card,22,211,1196,219,105,965,870,158);cardText(card,w/2,1040,titleFor(g.score),74);[[30,70,`得分 ${Math.round(g.score)}`],[430,395,`连涨 x${g.maxCombo}`],[834,720,`牛市 ${g.bullCount}次`]].forEach(([sx,dx,label])=>{cardPanel(card,sx,482,380,137,dx,1130,290,92);cardText(card,dx+145,1176,label,28)});card.save();card.globalAlpha=.95;card.drawImage(shareImages.ui,142,1080,860,150,92,1265,655,102);card.restore();cardText(card,418,1306,'牛来，终将抵达。',50);drawQrPlaceholder(card);cardPanel(card,31,675,810,185,747,1374,278,58);cardText(card,886,1402,'挑战 10000 点',26);shareCardBlob=await new Promise(resolve=>c.toBlob(resolve,'image/png'));}
  function saveShareCard(){if(!shareCardBlob)return;const href=URL.createObjectURL(shareCardBlob),link=document.createElement('a');link.href=href;link.download=`牛来战报-${Math.round(g.index)}点.png`;document.body.append(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(href),500)}
  function playBgm(){const begin=()=>{if(bgm.currentTime<BGM_LOOP_AT||bgm.ended)bgm.currentTime=BGM_LOOP_AT;bgm.muted=muted;bgm.play().catch(()=>{})};if(bgm.readyState>=1)begin();else bgm.addEventListener('loadedmetadata',begin,{once:true});}
  function beep(freq,duration){if(muted||!audio)return;const o=audio.createOscillator(),gain=audio.createGain();o.frequency.value=freq;o.type='sine';gain.gain.setValueAtTime(.04,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);o.connect(gain).connect(audio.destination);o.start();o.stop(audio.currentTime+duration)}
  ui.startBtn.onclick=()=>{initAudio();start()};ui.restart.onclick=()=>{initAudio();start()};ui.challenge.onclick=()=>{initAudio();start()};ui.share.onclick=async()=>{ui.share.disabled=true;ui.share.textContent='生成中…';try{await buildShareCard();ui.cardPanel.hidden=false}catch(error){console.error(error);ui.share.textContent='生成失败'}finally{ui.share.disabled=false;if(ui.share.textContent!=='生成失败')ui.share.textContent='生成分享图'}};ui.saveCard.onclick=saveShareCard;ui.closeCard.onclick=()=>ui.cardPanel.hidden=true;
  ui.mute.onclick=()=>{muted=!muted;bgm.muted=muted;localStorage.setItem('niulai-muted',muted?'1':'0');ui.mute.textContent=muted?'♩':'♫';ui.mute.setAttribute('aria-pressed',String(muted))};ui.mute.textContent=muted?'♩':'♫';bgm.muted=muted;bgm.addEventListener('timeupdate',()=>{if(bgm.duration&&bgm.currentTime>=bgm.duration-.12){bgm.currentTime=BGM_LOOP_AT;bgm.play().catch(()=>{})}});bgm.addEventListener('ended',()=>{bgm.currentTime=BGM_LOOP_AT;bgm.play().catch(()=>{})});
  addEventListener('keydown',e=>{if(['ArrowLeft','ArrowRight','a','d','A','D'].includes(e.key)){keys.add(e.key.toLowerCase()==='a'||e.key.toLowerCase()==='d'?e.key.toLowerCase():e.key);e.preventDefault()}});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()==='a'||e.key.toLowerCase()==='d'?e.key.toLowerCase():e.key));canvas.addEventListener('pointerdown',e=>{if(state==='PLAYING'||state==='BULL_MODE'){pointer=screenPoint(e);canvas.setPointerCapture?.(e.pointerId);e.preventDefault()}});canvas.addEventListener('pointermove',e=>{if(pointer!==null)pointer=screenPoint(e)});canvas.addEventListener('pointerup',()=>pointer=null);canvas.addEventListener('pointercancel',()=>pointer=null);
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&(state==='PLAYING'||state==='BULL_MODE')){g.resumeState=state;state='PAUSED';cancelAnimationFrame(raf)}else if(!document.hidden&&state==='PAUSED'){state=g.resumeState||'PLAYING';last=performance.now();raf=requestAnimationFrame(loop)}});
  Promise.all(assets.map(([key,path])=>load(key,ASSET+path))).then(()=>{reset();g.playerX=W/2;draw()});
})();
